/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models

import org.openapitools.client.models.StatusProcTrSubXy

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Status of sub-property of frame processor Translate
 *
 * @param L 
 * @param R 
 */


data class StatusProcTrSub (

    @Json(name = "L")
    val L: StatusProcTrSubXy? = null,

    @Json(name = "R")
    val R: StatusProcTrSubXy? = null

) {


}

