/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Which camera is being used or can be used
 *
 * Values: BOTH,L,R
 */

@JsonClass(generateAdapter = false)
enum class StatusCams(val value: kotlin.String) {

    @Json(name = "BOTH")
    BOTH("BOTH"),

    @Json(name = "L")
    L("L"),

    @Json(name = "R")
    R("R");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is StatusCams) "$data" else null

        /**
         * Returns a valid [StatusCams] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): StatusCams? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}

