/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Status of sub-property of frame processor Brightness-and-Contrast
 *
 * @param min 
 * @param max 
 * @param `val` 
 * @param supported 
 */


data class StatusProcBncSub (

    @Json(name = "min")
    val min: kotlin.Int? = null,

    @Json(name = "max")
    val max: kotlin.Int? = null,

    @Json(name = "val")
    val `val`: kotlin.Int? = null,

    @Json(name = "supported")
    val supported: kotlin.Boolean? = null

) {


}

