/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * X and Y translations for frame processor Translate
 *
 * @param x 
 * @param y 
 */


data class StatusProcTrSubXy (

    @Json(name = "x")
    val x: kotlin.Int? = null,

    @Json(name = "y")
    val y: kotlin.Int? = null

) {


}

