/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Image resolution
 *
 * @param h 
 * @param w 
 */


data class StatusResolution (

    @Json(name = "h")
    val h: kotlin.Int? = null,

    @Json(name = "w")
    val w: kotlin.Int? = null

) {


}

