/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Camera ready flags
 *
 * @param L 
 * @param R 
 */


data class StatusCameraReady (

    @Json(name = "L")
    val L: kotlin.Boolean? = null,

    @Json(name = "R")
    val R: kotlin.Boolean? = null

) {


}

