/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.openapitools.client.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Status of frame processor Calibration
 *
 * @param done 
 * @param running 
 * @param showCalibChessboardPoints 
 */


data class StatusProcCal (

    @Json(name = "done")
    val done: kotlin.Boolean? = null,

    @Json(name = "running")
    val running: kotlin.Boolean? = null,

    @Json(name = "showCalibChessboardPoints")
    val showCalibChessboardPoints: kotlin.Boolean? = null

) {


}

